package hibernatemysqlpersistency;

import java.math.BigDecimal;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

    private Integer staffId;
    private String name;
    private int age;
    private String address;
    private BigDecimal salary;

    public Staff() {
    }

    public Staff(String name, int age, String address) {
        this.name = name;
        this.age = age;
        this.address = address;
    }

    public Staff(String name, int age, String address, BigDecimal salary) {
        this.name = name;
        this.age = age;
        this.address = address;
        this.salary = salary;
    }

    public Integer getStaffId() {
        return this.staffId;
    }

    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public BigDecimal getSalary() {
        return this.salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    @Override
    public String toString() {
    return "[" + "staffId: " + staffId + ", name: " + name + ", age: " + age + ", address: " + address + ", salary: " + salary + "]";
    }
}
